name: Deploy production

on:
  push:
    branches:
      - "master"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build-front:
    name: Build front
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push front
      uses: docker/build-push-action@v3
      with:
        context: front
        file: Dockerfile
        push: true
        tags: numerisisep/numeris-front:prod
        cache-from: type=gha
        cache-to: type=gha

  build-back:
    name: Build back
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push back
      uses: docker/build-push-action@v3
      with:
        context: back
        file: Dockerfile.production
        push: true
        tags: numerisisep/numeris-back:prod
        cache-from: type=gha
        cache-to: type=gha


  pull-and-recreate:
    name: Pull and recreate
    needs:
      - build-front
      - build-back
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd numeris
          git pull
          docker-compose -f docker-compose.infra.yml pull
          docker-compose -f docker-compose.infra.yml up -d --force-recreate
